### ISSUE TITLE
Mawk manpage 1.3.3

### ISSUE THREAD

**Issue by svnpenn** [ThomasDickey/mawk-snapshots#1]
Mawk manpage 1.3.4 is here:

http://invisible-island.net/mawk/manpage/mawk.html

However that version has not seen wide adoption:

http://github.com/svnpenn/velour/blob/master/doc/mawk.md

Is the older 1.3.3 manpage available to view?

**Comment by ThomasDickey** [comment]
https://github.com/ThomasDickey/mawk-snapshots
https://invisible-island.net/personal/git-exports.html

**Comment by svnpenn** [comment]
To any interested, it looks like this is the last version before changes are
introduced that break from current Debian/Ubuntu version:

http://github.com/ThomasDickey/mawk-snapshots/blob/t20091213h/man/mawk.1
