### ISSUE TITLE
Add tags

### ISSUE THREAD

**Issue by svnpenn** [ThomasDickey/mawk-snapshots#2]
I see several "tags" have been committed:

- label t20171017
- label t20161120
- label t20161107
- label t20160930
- label t20160927

but they have not been tagged:

http://github.com/ThomasDickey/mawk-snapshots/tags

**Comment by ThomasDickey** [comment]
The link I mentioned in the first issue points out that mawk-snapshots is generated.

**Comment by ThomasDickey** [comment]
I pushed those out, and added a to-do item for the other snapshot-repos.

**Comment by svnpenn** [comment]
nice! thanks
