### ISSUE TITLE
Fix in "bi_mktime()" in commit c33bfd2 was not good

### ISSUE THREAD

**Issue by kwanyyoss** [ThomasDickey/mawk-snapshots#5]
[c33bfd2](https://github.com/ThomasDickey/mawk-snapshots/commit/c33bfd24a876af8c3099d03e10382edda1a518ad#diff-ff22f4befba8425974e6498cc3b87f6c)

If "sval" were NULL, after jumping to "error:", the line:
```TRACE(("...bi_mktime(%s) ->%s", sval->str, ctime(&result)));```
would dereference the NULL "sval".

If I were you, I would do a minimal fix like this:
```
@@ -471,6 +471,10 @@

     TRACE_FUNC("bi_mktime", sp);

+    if (!sval) {
+        result = -1;
+        goto bi_mktime_done;
+    }
     memset(&my_tm, 0, sizeof(my_tm));
     switch (sscanf(sval->str, "%d %d %d %d %d %d %d",
                   &my_tm.tm_year,
@@ -498,7 +502,7 @@
        result = mktime(&my_tm);
     }
     TRACE(("...bi_mktime(%s) ->%s", sval->str, ctime(&result)));
-
+bi_mktime_done:
     cell_destroy(sp);
     sp->type = C_DOUBLE;
     sp->dval = (double) result;
```

**Comment by ThomasDickey** [comment]
thanks - but the bug-reporting for this is https://github.com/ThomasDickey/original-mawk/issues
